languageCode = "en-us"
title = "FuTRES"
theme = ["futres", "kube"]
homepageText = "FuTRES"
publishDir = "docs"
sectionPagesMenu = "main"
googleAnalytics = "G-CPLCJWRNNH"

[markup.goldmark.renderer] 
  unsafe= true

[menu]

  [[menu.main]]
    name = "Get Involved"
    identifier = "get_involved"
    weight = 1

  [[menu.main]]
    name = "Data Tutorial"
    parent = "get_involved"
    weight = 1
    identifier = "data_tutorial"
    url = "https://futreswebsite.netlify.com/data_tutorial/"

  [[menu.main]]
    name = "Term Request"
    parent = "get_involved"
    weight = 1
    identifier = "term_request"
    url = "https://github.com/futres/fovt/issues/new"

  [[menu.main]]
    name = "About Us"
    identifier = "about_us"
    weight = 2

  [[menu.main]]
    name = "About"
    parent = "about_us"
    identifier = "read_more"
    weight = 2
    url = "/read_more/"

  [[menu.main]]
    name = "How It Works"
    parent = "about_us"
    identifier = "how_it_works"
    weight = 2
    url = "https://futreswebsite.netlify.com/how_it_works/"

    [[menu.main]]
    name = "Team"
    parent = "about_us"
    weight = 2
    identifier = "team"
    url = "https://futreswebsite.netlify.com/team/"

  [[menu.main]]
    name = "News"
    parent = "about_us"
    weight = 2 
    identifier = "news"
    url = "https://futreswebsite.netlify.com/news/"

  [[menu.main]]
    name = "Contact Us"
    parent = "about_us"
    weight = 2 
    identifier = "contact"
    url = "https://futreswebsite.netlify.com/contact/"

  [[menu.main]]
    name = "Research"
    identifier = "research"
    weight = 3

  [[menu.main]]
    name = "Community Projects"
    parent = "research"
    weight = 3
    identifier = "community_projects"
    url = "https://futreswebsite.netlify.com/usecases/"

  [[menu.main]]
    name = "Contributed Data"
    parent = "research"
    weight = 3
    identifier = "contributed-data"
    url = "https://futreswebsite.netlify.com/contributed-data/"

  [[menu.main]]
    name = "Talks & Papers"
    parent = "research"
    weight = 3
    identifier = "publish"
    url = "https://futreswebsite.netlify.com/publish/"

  [[menu.main]]
    name = "Resources"
    identifier = "resources"
    weight = 4

  [[menu.main]]
    name = "Data Dashboard"
    parent = "resources"
    weight = 4
    identifier = "dashboard"
    url = "https://futreswebsite.netlify.com/dashboard/"

  [[menu.main]]
    name = "rFuTRES"
    parent = "resources"
    weight = 4
    identifier = "rfutres"
    url = "https://github.com/futres/rfutres"

  [[menu.main]]
    name = "RShiny App"
    parent = "resources"
    weight = 4
    identifier = "rshiny"
    url = "https://futres.shinyapps.io/pyConvApp/"

  [[menu.main]]
    name = "Youtube Channel"
    parent = "resources"
    weight = 4
    identifier = "youtube"
    url = "https://futreswebsite.netlify.com/youtube/"

  [[menu.main]]
    name = "Workshops"
    weight = 5
    identifier = "workshop"

  [[menu.main]]
    parent = "workshop"
    name = "Workshop Information"
    weight = 5
    identifier = "workshopinfo"
    url = "https://futreswebsite.netlify.com/workshop/"
    
  [[menu.main]]
    parent = "workshop"
    name = "Past Workshops"
    weight = 5
    identifier = "past_workshops"
    url = "https://futreswebsite.netlify.com/past_workshops/"
  
  [[menu.main]]
    name = "Code of Conduct"
    parent = "workshop"
    weight = 5
    identifier = "codeofconduct"
    url = "https://futreswebsite.netlify.com/codeofconduct/"


