baseURL = "https://futreswebsite.netlify.com/"
languageCode = "en-us"
title = "FuTRES"
theme = ["futres", "kube"]
homepageText = "FuTRES"
publishDir = "docs"

[[menu.main]]
  name = "How It Works"
  weight = -8
  identifier = "how"
  url = "/how/"

[[menu.main]]
  name = "Team"
  weight = -7
  identifier = "team"
  url = "/team/"

[[menu.main]]
  name = "Workshops"
  weight = -6
  identifier = "workshop"
  url = "/workshop/"
  
[[menu.main]]
  parent = "team"
  name = "Participants & Organizers"
  weight = -5
  identifier = "biosketch"
  url = "/biosketch/"

[[menu.main]]
  name = "Code of Conduct"
  parent = "workshop"
  weight = -4
  identifier = "codeofconduct"
  url = "/codeofconduct/"

[[menu.main]]
  name = "Use Cases"
  parent = "products"
  weight = -3
  identifier = "usecases"
  url = "/usecases/"

[[menu.main]]
  name = "Data"
  parent = "products"
  weight = -2
  identifier = "data"
  url = "/data/"

[[menu.main]]
  name = "Products"
  weight = -2
  identifier = "products"
  url = "/products/"

#[[menu.main]]
#  name = "Query"
#  weight = -1
#  identifier = "query"
#  url = "/query/"
