baseURL = "https://futreswebsite.netlify.com/"
languageCode = "en-us"
title = "FuTRES"
theme = ["futres","kube"]
homepageText = "FuTRES"
publishDir = "docs"

[[menu.main]]
  name = "How It Works"
  weight = -6
  identifier = "how"
  url = "/how/"

[[menu.main]]
  name = "Team"
  weight = -5
  identifier = "team"
  url = "/team/"

[[menu.main]]
  name = "Workshops"
  weight = -4
  identifier = "workshop"
  url = "/workshop/"

[[menu.main]]
  name = "Use Cases"
  weight = -3
  identifier = "usecases"
  url = "/usecases/"

[[menu.main]]
  name = "Data"
  weight = -2
  identifier = "data"
  url = "/data/"

#[[menu.main]]
#  name = "Query"
#  weight = -1
#  identifier = "query"
#  url = "/query/"
